using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Umb.Options
{
    public class UmbEnum
    {
        public enum UmbOptions
        {
            Layouts_Above = 0,
            Layouts_Boxed = 1,
            ItemsPerRow_4 = 2,
            ItemsPerRow_3 = 3,
            ItemsPerRow_2 = 4,
            ItemsPerRow_1 = 5,
            TextAlignment_Left = 6,
            TextAlignment_Center = 7,
            TextAlignment_Right = 8,
            BannerSize_Takeover = 9,
            BannerSize_Medium = 10,
            BannerSize_Short = 11,
            PageLayout_Left = 12,
            PageLayout_Right = 13,
            PageLayout_Center = 14,
            PageLayout_CenterAlt = 15,
            PageLayout_Wide = 16,
            ListingStyle_Grid = 17,
            ListingStyle_Vertical = 18,
            TextPosition_Before = 19,
            TextPosition_After = 20,
            ComponentWidth_Center = 21,
            ComponentWidth_Wide = 22,
            ComponentWidth_Full = 23,
            RepeatableLayout_Tabbed = 24,
            RepeatableLayout_Accordion = 25,
            WindowsOrder_4_Big = 26,
            WindowsOrder_4_Small = 27,
            WindowsOrder_3_Big = 28,
            WindowsOrder_3_Small = 29,
            WindowsOrder_4 = 30,
            WindowsOrder_3 = 31,
            WindowsOrder_2 = 32,
            WindowsOrder_1 = 33,
            SplitComponent_Even = 34,
            SplitComponent_7030 = 35,
            SplitComponent_3070 = 36,
            Newsletter_CM = 37,
            Newsletter_Mailchimp = 38,
            BG_Cover = 39,
            BG_FullWidth = 40,
            BG_Auto = 41,
            BG_Repeat = 42,
            BG_RepeatX = 43,
            BG_RepeatY = 44,
            BG_TopLeft = 45,
            BG_TopCenter = 46,
            BG_TopRight = 47,
            BG_CenterLeft = 48,
            BG_CenterCenter = 49,
            BG_CenterRight = 50,
            BG_BottomLeft = 51,
            BG_BottomCenter = 52,
            BG_BottomRight = 53,
            Sitemap_Always = 54,
            Sitemap_Hourly = 55,
            Sitemap_Daily = 56,
            Sitemap_Weekly = 57,
            Sitemap_Monthly = 58,
            Sitemap_Yearly = 59,
            Sitemap_Never = 60,
            ReusableComponentStyle_Tabbed = 61,
            ReusableComponentStyle_Stacked = 62,
            ImageStyle_Square = 63,
            ImageStyle_Landscape = 64,
            ImageStyle_Portrait = 65,
            ImageStyle_Circle = 66,
            ImageStyle_Wide = 67,
            IconShape_Square = 68,
            IconShape_Circle = 69,
            IconShape_Rounded = 70,
            EMPTY = 71,
            ListingStyle_Single = 72,
        }
    }
}
